//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Menedger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentation
    {
        public int id_Documentation { get; set; }
        public int id_Status { get; set; }
        public int id_Project { get; set; }
        public string Progress { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Profit { get; set; }
    
        public virtual Production_Project Production_Project { get; set; }
        public virtual Statuss Statuss { get; set; }
    }
}
