//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Menedger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class is1_25_kokorinds_Kursovoy_ProjectEntities1 : DbContext
    {
        public is1_25_kokorinds_Kursovoy_ProjectEntities1()
            : base("name=is1_25_kokorinds_Kursovoy_ProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documentation> Documentation { get; set; }
        public virtual DbSet<Eventt> Eventt { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Priorityy> Priorityy { get; set; }
        public virtual DbSet<Production_Project> Production_Project { get; set; }
        public virtual DbSet<Project_Team> Project_Team { get; set; }
        public virtual DbSet<Resource_Type> Resource_Type { get; set; }
        public virtual DbSet<Resourcee> Resourcee { get; set; }
        public virtual DbSet<Rolee> Rolee { get; set; }
        public virtual DbSet<Statuss> Statuss { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Userr> Userr { get; set; }
    }
}
