//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Menedger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id_News { get; set; }
        public string Heading { get; set; }
        public string Descriptionn { get; set; }
        public System.DateTime Publication_Date { get; set; }
        public int id_User { get; set; }
    
        public virtual Userr Userr { get; set; }
    }
}
