//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Menedger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Production_Project()
        {
            this.Documentation = new HashSet<Documentation>();
            this.Project_Team = new HashSet<Project_Team>();
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int id_Project { get; set; }
        public string Namee { get; set; }
        public string Descriptionn { get; set; }
        public System.DateTime Start_Datee { get; set; }
        public Nullable<System.DateTime> End_Datee { get; set; }
        public decimal Budget { get; set; }
        public int id_Status { get; set; }
        public int id_Resource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentation> Documentation { get; set; }
        public virtual Resourcee Resourcee { get; set; }
        public virtual Statuss Statuss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Team> Project_Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
