//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Menedger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Team
    {
        public int id_Project_Team { get; set; }
        public Nullable<int> id_Project { get; set; }
        public Nullable<int> id_User { get; set; }
    
        public virtual Production_Project Production_Project { get; set; }
        public virtual Userr Userr { get; set; }
    }
}
