//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Menedger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resourcee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resourcee()
        {
            this.Production_Project = new HashSet<Production_Project>();
        }
    
        public int id_Resource { get; set; }
        public Nullable<int> id_Resource_Type { get; set; }
        public string Namee { get; set; }
        public string Descriptionn { get; set; }
        public string Availabilityy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Project> Production_Project { get; set; }
        public virtual Resource_Type Resource_Type { get; set; }
    }
}
