//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Menedger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int id_Tasks { get; set; }
        public int id_Project { get; set; }
        public string Namee { get; set; }
        public string Descriptionn { get; set; }
        public int id_Priority { get; set; }
        public System.DateTime Start_Datee { get; set; }
        public Nullable<System.DateTime> End_Datee { get; set; }
        public int id_Status { get; set; }
        public string Time_Spent { get; set; }
        public int id_User { get; set; }
    
        public virtual Priorityy Priorityy { get; set; }
        public virtual Production_Project Production_Project { get; set; }
        public virtual Statuss Statuss { get; set; }
        public virtual Userr Userr { get; set; }
    }
}
